name: publish

on:
  push:
    branches:
      - main

env:
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        if: env.REGISTRY_USERNAME != ''
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        if: env.REGISTRY_USERNAME != ''
        uses: docker/build-push-action@v6
        with:
          outputs: "type=registry"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quay.io/terraform-docs/gh-actions:edge

  release-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
